### ISSUE TITLE
Investigate mutating webhook & non-proxying sidecar pattern for service binding

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud-incubator/mononoke#19]
**Stretch Goal**
This pattern has been used by [HashiCorp vault](https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/) to inject secrets into a running Pod

A simple k8s controller could be used to reconcile `ServiceBinding` events. A simplified example might be;

* A `MySqlServiceBinding` resource is created for the `SpringBootApplication`
* The controller creates a user account in the running MySQL database
* The `SpringBootApplication` has an init container that will populate secrets by requesting and `ServiceBinding` resources that apply to the app
* The `SpringBootApplication` has a second container (a non-proxying sidecar). This will be notified by the `ServiceBinding` controller when a secret changes and will trigger a graceful restart of the app to pick up changes

**Comment by ojhughes** [comment]
Google k8s config connector has a similar pattern where a secretRef is provided with the binding and the reconciler creates the credential and then populates that secret 
https://cloud.google.com/config-connector/docs/how-to/secrets#passing_a_secret_to_a_resource

**Comment by ojhughes** [comment]
The RedHat service binding operator is interesting as it should work across multiple platforms and also provides a mechanism for backing services to advertise themselves as bindable

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: service-binding-demo
spec:
  applicationSelector:
    resourceRef: nodejs-rest-http-crud
    group: apps
    version: v1
    resource: deployments
  backingServiceSelector:
    group: postgresql.baiju.dev
    version: v1alpha1
    kind: Database
    resourceRef: db-demo
```

see https://developers.redhat.com/blog/2019/12/19/introducing-the-service-binding-operator/
