### ISSUE TITLE
SpringBootApplication -> SpringBootContainer

### ISSUE THREAD

**Issue by scothis** [spring-cloud-incubator/mononoke#28]
The SpringBootApplication resource encapsulates out knowledge and opinions about running a Spring Boot application as a container on k8s. It does this by hosting a PodTemplateSpec on its spec and creating a Deployment with the original PodTemplateSpec injected with opinions. This has a few issues:

- it only supports Deployments
- there are plenty of fields on Deployment that we don't handle
- it only supports Deployments!
- all we interact with is the PodTemplateSpec
- it only supports Deployments!!

We can invert the relationship between the SpringBootApplication and a "Deployment", and still be able to inject the same opinions. Introducing the SpringBootContainer:

```yaml
apiVersion: apps.mononoke.local/v1alpha1
kind: SpringBootContainer
metadata:
  name: petclinic
spec:
  containerName: application
  subject:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic
  applicationProperties: {}
status:
  applicationPropertiesRef:
    name: petclinic-application-properties-rkgds
  appliedOpinions:
  - spring-boot
  - spring-boot-graceful-shutdown
  - spring-web-port
  - spring-boot-actuator
  - spring-boot-actuator-probes
  ...
```

Deployment before injection:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: application
          image: scothis/petclinic
          resources:
            limits:
              memory: 512Mi
```

Deployment after injection:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      annotations:
        boot.spring.io/actuator: http://:9001/actuator
      labels:
        app: petclinic
        boot.spring.io/version: 2.2.4.RELEASE
    spec:
      containers:
      - name: application
        image: scothis/petclinic@sha256:e27021462eb50698890cdf1dda187406c0535a8c2f259f9cacc3a5d4f1ca52e9
        resources:
          limits:
            memory: 512Mi
        env:
        - name: JAVA_OPTS
          value: -Dspring.profiles.include=mononoke
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/info
            port: 9001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 9001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /workspace/BOOT-INF/classes/application-mononoke.properties
          name: mononoke-properties
          readOnly: true
          subPath: application.properties
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: petclinic-application-properties-rkgds
        name: mononoke-properties
```

application properties ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    apps.mononoke.local/spring-boot-container: petclinic
  name: petclinic-application-properties-rkgds
data:
  application.properties: |
    # Generated by mononoke. DO NOT EDIT.
    management.endpoint.health.enabled = true
    management.endpoint.info.enabled = true
    management.endpoints.web.base-path = /actuator
    management.server.port = 9001
    management.server.ssl.enabled = false
    server.port = 8080
    server.shutdown.grace-period = 24s
```

By the SpringBootContainer defining a reference to the Deployment, we can interact with any resource the hosts a PodTemplateSpec, while providing the same high level experience. The downside is that users will need to specify the apiVersion, kind and name of the resource they want to target. In the future we might be able to provide a more cross-cutting mechanism to apply opinions.

To implement this behavior, we need to switch to the Knative Binding reconcile framework. This is only a compile time dependency within the controller, not a dependency on Knative at runtime. Unfortunately, it is incompatible with the controller-runtime foundation we currently use, so this is an invasive change.
